server:
  port: 8090

spring:
  datasource:
    url: jdbc:sqlserver://localhost:${SQL_PORT:1433};databaseName=${SQL_DB:BooksDB};integratedSecurity=false;Encrypt=false;TrustServerCertificate=false;
    username: ${SQL_USERNAME:sa}
    password: ${SQL_PASSWORD:root123}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    hikari: 
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
  application:
    name: book
     
      

  jpa:
    hibernate.ddl-auto: update
#    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

  autoconfigure:    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      
  profiles:
    active: book
    
springdoc:
  packagesToScan: com.example.books
  pathsToMatch: /**, /v1
  # swagger-ui custom path
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true
  show-login-endpoint: false
  
  
#security:
#  basic:
#    enable: false
#  ignored: /**

  